'''
WHEN THE AUTOMATED SYSTEM UPLOADS FILES NUMERICALLY,
THE NAME INCREMENTS BY 1 FOR EACH NEW UPLOAD

WHEN 9999 FILES HAVE BEEN UPLOADED, THE SOFTWARE CAN NO LONGER
UPLOAD NEW ONES, NECESSITATING THE NEED FOR A NEW DIRECTORY TO BE CREATED.

INSTEAD OF A PERSON HAVING TO CHECK THE FILE SYSTEMS EVERY DAY/WEEK/MONTH/GUESSING WHEN IT'S FULL, THIS SCRIPT WILL AUTOMATICALLY
FIRE OFF AN EMAIL TO AN ADMINISTRATOR ALTERTING THEM WHENEVER A DIRECTORY HAS REACHED 9999 UPLOADS.

THIS BOTH KEEPS ALL DIRECTORIES MANAGEABLE (LESS THAN 1000 FILES) AND ALLOWS ADMINS TO BETTER 
ORGANIZE FILE SYSTEMS BASED ON DIFFERENT DESCRIPTORS

'''
import os, re

target = re.compile(".........9999") 

path = 'C:/Users/Robert/downloads/test_case'

entire_folder = os.listdir(path)

for matches in re.findall(target, path):
	print(matches)
	'''



	CONFIDENTIAL SMPTP EMAIL CREDENTIALS GO HERE. THE REMAINDER OF THE SCRIPT
	SENDS AN EMAIL TO THE ADMIN WHEN THE FILE IS FOUND



	'''



